@extends('layouts.app')



<!doctype html>
<html class="h-full bg-gray-50">

<head>
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="{{ asset('js/icons.js') }}" cross-origin="anonymous" defer></script>
    <script src="{{ asset('js/pace.js') }}" defer></script>

    <!-- Stylesheets -->
    <link href="{{ asset('css/pace.css') }}" rel="stylesheet">

    @notifyCss

</head>



<body class="h-full">
  
        <x:notify-messages />
        @notifyJs
    <div class="min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
        <div class="max-w-md w-full space-y-8">
            <div>
                <img class="mx-auto h-12 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg"
                    alt="Workflow">
                <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
                   Verify Your Phone Number
                </h2>
                <p class="mt-2 text-center text-sm text-gray-600">
                    Enter the code we’ve sent to <span class="font-bold">{{ Auth::user()->mobile_number }}</span>, Didn’t receive the code?
                </p>
                <p class="mt-2 text-center text-sm text-gray-600">
                   <a href="" class=" no-underline">Change phone number</a> or <a href="" class=" no-underline">request a call</a>                </p>
            </div>
         
            <div class="mt-8 space-y-6">

<form action="" method="POST">
    @csrf <!-- {{ csrf_field() }} -->
    <!-- This is the div where the otp fields are generated by Javascript -->
    <div class="flex justify-center " id="OTPInput">
    </div>
    <!-- Change this name attribute to mach your form submission parameters. Make sure you update the id in the javascript code if any changes are made to the id attribute -->
    <input hidden id="otp" name="otpcode" value="">
    <button  id="otpSubmit" name="verifyotpbtn"
    class="group relative mt-4 w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
    <span class="absolute left-0 inset-y-0 flex items-center pl-3">
        <!-- Heroicon name: solid/lock-closed -->
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 18h.01M8 21h8a2 2 0 002-2V5a2 2 0 00-2-2H8a2 2 0 00-2 2v14a2 2 0 002 2z" />
          </svg>
    </span>
   {{ __(' Verify Me') }}
</button>
<div class="text-sm text-center mt-3">
                        
    <a href="{{('resend')}}" class="font-medium text-gray-600 hover:text-indigo-500 no-underline ">
        <i class="fas fa-redo-alt"></i>
                        {{__('Resend code')}}
    </a>
    
  </div>
  @error('email')
  <span class="invalid-feedback" role="alert">
      <strong>{{ $message }}</strong>
  </span>
@enderror

  </form>

                   

             

  <script src="{{ asset('js/phone_input.js') }}" defer></script>


  
</body>
